'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PaymentConfirm

    '''<summary>
    '''LabelFirstNameD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFirstNameD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFirstName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelLastNameD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLastNameD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLastName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelAddressD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAddressD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCityD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCityD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelZipD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelZipD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelZip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelStateProvinceD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStateProvinceD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCountryD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCountryD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCountry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonGoBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonGoBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelTransactionAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTransactionAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonSubmitPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSubmitPayment As Global.System.Web.UI.WebControls.Button
End Class
