'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConferenceFromURL
    
    '''<summary>
    '''SqlDataSourceConf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceConf As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''hdnConfName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnConfName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnConfShortName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnConfShortName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnConfDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnConfDates As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnConfLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnConfLocation As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnExampleAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnExampleAbstract As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnTechnicalScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTechnicalScope As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnFinalPlacement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFinalPlacement As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnPreliminaryProgram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPreliminaryProgram As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnConferenceEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnConferenceEmail As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''imgBanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBanner As Global.System.Web.UI.WebControls.Image
End Class
