'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SessionHandler
    
    '''<summary>
    '''PanelParticipationControlHandler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelParticipationControlHandler As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ParticipationIDLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParticipationIDLogin As Global.Battelle.ParticipationIDLogin
    
    '''<summary>
    '''divOverlay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOverlay As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divSessionTimeoutWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSessionTimeoutWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''UpdatePanelHandler1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelHandler1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblSessionWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSessionWarning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSessionWarning2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSessionWarning2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSessionWarning3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSessionWarning3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnContinueWorking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinueWorking As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnLogInAgain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogInAgain As Global.System.Web.UI.WebControls.Button
End Class
