'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AbstractsForm
    
    '''<summary>
    '''hdnEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEmail As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnEmail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEmail2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''PanelAbstractTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAbstractTop As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''SqlDataSourceSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSession As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceRequested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRequested As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lnkExampleAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExampleAbstract As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkTechnicalScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTechnicalScope As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lblConference2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConference2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblConference3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConference3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkSubjectEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSubjectEmail As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''btnBegin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBegin As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PanelParticipationControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelParticipationControl As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblParticipantCodeNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParticipantCodeNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ParticipationIDLoginAbstracts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParticipationIDLoginAbstracts As Global.Battelle.ParticipationIDLogin
    
    '''<summary>
    '''UpdatePanelAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAbstract As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanelAbstractsMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAbstractsMain As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''SqlDataSourceLookupCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceLookupCountry As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceLookupStateProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceLookupStateProvince As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lnkSubjectEmail3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSubjectEmail3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''LabelAbstractValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAbstractValidation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LiteralAlertDivOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralAlertDivOpen As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblCorPresAuthor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorPresAuthor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnCorPres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCorPres As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblCorPresAuthorWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorPresAuthorWarning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LiteralAlertDivClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralAlertDivClose As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblAuthors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAuthors As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxAbstractAuthors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxAbstractAuthors As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''ButtonAuthorsAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAuthorsAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonCorPresAuthorSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCorPresAuthorSet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonAuthorsRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAuthorsRemove As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PanelPersonAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelPersonAdd As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblPersonEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPersonEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxPersonEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPersonEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LinkButtonPersonLookup2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonPersonLookup2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonSearchCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSearchCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LabelPersonLookupResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPersonLookupResult As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FormViewPersonLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormViewPersonLookup As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''SqlDataSourcePersonLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourcePersonLookup As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadEditorAbstractTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadEditorAbstractTitle As Global.Telerik.Web.UI.RadEditor
    
    '''<summary>
    '''lblAuthorList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAuthorList As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxAuthorList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAuthorList As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFinalPlacement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalPlacement As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPreferredFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPreferredFormat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadioButtonListAbstractFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonListAbstractFormat As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''SqlDataSourceAbstractFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAbstractFormat As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblSubReqBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubReqBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlRequestedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRequestedBy As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblAppTopics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppTopics As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkTechProgScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTechProgScope As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''ddlApplicableTopics1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlApplicableTopics1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlApplicableTopics2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlApplicableTopics2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblNewTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewTopic As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxAbstractNewTopicArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAbstractNewTopicArea As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTitleAuthorBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitleAuthorBlock As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadEditorAbstractTitleAuthorBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadEditorAbstractTitleAuthorBlock As Global.Telerik.Web.UI.RadEditor
    
    '''<summary>
    '''lblAbstractBackground control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAbstractBackground As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadEditorAbstractBackground control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadEditorAbstractBackground As Global.Telerik.Web.UI.RadEditor
    
    '''<summary>
    '''lblAbstractApproach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAbstractApproach As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadEditorAbstractApproach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadEditorAbstractApproach As Global.Telerik.Web.UI.RadEditor
    
    '''<summary>
    '''lblAbstractResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAbstractResults As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadEditorAbstractResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadEditorAbstractResults As Global.Telerik.Web.UI.RadEditor
    
    '''<summary>
    '''lblUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpload As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FileUploadAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploadAbstract As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''RegularExpressionValidatorUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidatorUpload As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''ButtonSubmitAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSubmitAbstract As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PanelAbstractConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAbstractConfirmation As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblMeetingPlannerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMeetingPlannerEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkSubjectEmail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSubjectEmail2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lblPlacementDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlacementDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelAbstractConfirmationResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAbstractConfirmationResult As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkNewAbstractKeepAuthors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNewAbstractKeepAuthors As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkNewAbstractNewAuthors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNewAbstractNewAuthors As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''UpdateProgressAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgressAbstract As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Battelle.Abstracts1
        Get
            Return CType(MyBase.Master,Battelle.Abstracts1)
        End Get
    End Property
End Class
