'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegForm
    
    '''<summary>
    '''lblConferenceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConferenceType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SqlDataSourceReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceReg As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''PanelParticipationControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelParticipationControl As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PanelParticipationControlTechReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelParticipationControlTechReg As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ParticipationIDLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParticipationIDLogin As Global.Battelle.ParticipationIDLogin
    
    '''<summary>
    '''PanelForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelForm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''SqlDataSourceFees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceFees As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlert As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFeesHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFeesHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFeesCover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFeesCover As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRegFeeIncrease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegFeeIncrease As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelMain As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rblIndustry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIndustry As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblIndustry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndustry As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblIndustryFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndustryFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblGovt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblGovt As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblGovt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGovt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGovtFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGovtFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblUniv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblUniv As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblUniv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUniv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUnivFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnivFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblStudent As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblStudentFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelOneTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelOneTime As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rblOneTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblOneTime As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblOneTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOneTimeFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneTimeFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPickDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPickDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkOneTimeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOneTimeDate As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''PanelExhibPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelExhibPass As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rblExhibPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblExhibPass As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblExhibPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExhibPass As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblExhibPassFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExhibPassFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPickDateExhibPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPickDateExhibPass As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkExhibPassDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExhibPassDate As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''rblExhibPassWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblExhibPassWeek As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblExhibPassWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExhibPassWeek As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblExhibPassWeekFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExhibPassWeekFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelTechReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelTechReg As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''SqlDataSourceOrgValidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceOrgValidate As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceGovNonProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceGovNonProfit As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''techRegFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents techRegFee As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''rblTechReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTechReg As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblTechReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechReg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTechRegFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechRegFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''techRegGovNonProfitFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents techRegGovNonProfitFee As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''rblTechRegGovNonProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTechRegGovNonProfit As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblTechRegGovNonProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechRegGovNonProfit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTechRegGovNonProfitRegFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechRegGovNonProfitRegFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTechRegDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechRegDiv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOrgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrgID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOrgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrgID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnOrgValidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrgValidate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblOrgValid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrgValid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ButtonOrgEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonOrgEmail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblTechRegDivClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechRegDivClose As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SqlDataSourcePersonIDFromEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourcePersonIDFromEmail As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''PanelOrgEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelOrgEmail As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblEnterEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnterEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxOrgEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxOrgEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonCheckOrgEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCheckOrgEmail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RequiredFieldValidatorEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LabelCheckEmailResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCheckEmailResult As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelWaived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelWaived As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rblWaived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblWaived As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblWaived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaived As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWaivedFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaivedFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWaivedNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaivedNotes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtWaiveNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWaiveNotes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblConferenceType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConferenceType2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblConferenceType3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConferenceType3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblConferenceType4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConferenceType4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDefunctSpecialNeeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDefunctSpecialNeeds As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSpecialNeeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpecialNeeds As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSpecialNeeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecialNeeds As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblConference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConference As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblConferenceType5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConferenceType5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkbtnPrivacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnPrivacy As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblConference2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConference2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkOptin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOptin As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblOptOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOptOut As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblConference3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConference3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ltl50PercentToDate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltl50PercentToDate3 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblConferenceType6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConferenceType6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ltl75PercentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltl75PercentDate As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltlServiceFee1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlServiceFee1 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltl50PercentFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltl50PercentFromDate As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltl50PercentToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltl50PercentToDate As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltlServiceFee2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlServiceFee2 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltl50PercentToDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltl50PercentToDate2 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblConferenceType7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConferenceType7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkRegTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRegTC As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''ltlRegTCAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlRegTCAlert As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''chkRegTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRegTC As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblRegTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegTC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlShortCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShortCourse As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ltlShortCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlShortCourse As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''chkShourtCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShourtCourse As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblShortCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShortCourse As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelPayment As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblRegistration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistration As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSpacer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpacer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSelectedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDate As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblSpecialNeeds2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpecialNeeds2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOptIn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOptIn2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''radPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radPayment As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidatorPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorPayment As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''btnNextPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextPay As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lnkbtnShowAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnShowAdmin As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''PanelAdminCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAdminCode As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblAdminDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminDiv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAdminCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAdminCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdminCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAdminCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdminCheck As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAdminValid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminValid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAdminDivClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminDivClose As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnNewStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNewStart As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''SqlDataSourceAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAttendance As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceLedger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceLedger As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''hdnVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVal As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFee As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnExhibID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnExhibID As Global.System.Web.UI.WebControls.HiddenField
End Class
