'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShortCourseProposal
    
    '''<summary>
    '''hdnEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEmail As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnEmail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEmail2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlert As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVal As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''PanelInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelInstructions As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PanelClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelClosed As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClosed As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelParticipationControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelParticipationControl As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ParticipationIDLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParticipationIDLogin As Global.Battelle.ParticipationIDLogin
    
    '''<summary>
    '''PanelTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelTerms As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblTermsMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTermsMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLiability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLiability As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TermsConditions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TermsConditions As Global.Battelle.ShortCourseProposalTerms
    
    '''<summary>
    '''chkTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTerms As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnAgree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgree As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''UpdatePanelAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAbstract As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanelForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelForm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''SqlDataSourceLookupCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceLookupCountry As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceLookupStateProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceLookupStateProvince As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lnkConferenceEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkConferenceEmail As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''LabelAbstractValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAbstractValidation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LiteralAlertDivOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralAlertDivOpen As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblCorPresInstructor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorPresInstructor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnCorPres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCorPres As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblCorPresInstructorWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorPresInstructorWarning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LiteralAlertDivClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralAlertDivClose As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblInstructors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInstructors As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxAbstractInstructors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxAbstractInstructors As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''ButtonInstructorsAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonInstructorsAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonCorPresInstructorSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCorPresInstructorSet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonInstructorsRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonInstructorsRemove As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PanelPersonAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelPersonAdd As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblPersonEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPersonEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxPersonEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPersonEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LinkButtonPersonLookup2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonPersonLookup2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonSearchCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSearchCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LabelPersonLookupResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPersonLookupResult As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FormViewPersonLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormViewPersonLookup As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''SqlDataSourcePersonLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourcePersonLookup As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCourseLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCourseLength As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblCourseLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCourseLength As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblLaptopsYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLaptopsYN As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblLaptopsYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblLaptopsYN As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblSoftwareYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoftwareYN As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblSoftwareYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSoftwareYN As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtSoftware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoftware As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblInternetYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInternetYN As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblInternetYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblInternetYN As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblSupplementaryMaterialsYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupplementaryMaterialsYN As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblSupplementaryMaterialsYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSupplementaryMaterialsYN As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtSupplementaryMaterials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplementaryMaterials As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblObjective control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObjective As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtObjective control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObjective As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverview As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverview As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblAgenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgenda As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAgenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgenda As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonSubmitAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSubmitAbstract As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PanelAbstractConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAbstractConfirmation As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblMeetingPlannerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMeetingPlannerEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ltlConferenceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlConferenceType As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltlConferenceType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlConferenceType2 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lnkSubjectEmail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSubjectEmail2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''LabelAbstractConfirmationResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAbstractConfirmationResult As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkNewAbstractKeepInstructors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNewAbstractKeepInstructors As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkNewAbstractNewInstructors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNewAbstractNewInstructors As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''UpdateProgressAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgressAbstract As Global.System.Web.UI.UpdateProgress
End Class
