'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminList

    '''<summary>
    '''lblConferenceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConferenceType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReturn As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''SqlDataSourceRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRoles As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceSessionNotFinalized control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSessionNotFinalized As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gvNotFinalized control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvNotFinalized As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSourceSessionFinalizedAccepted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSessionFinalizedAccepted As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gvFinalizedAccepted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFinalizedAccepted As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSourceSessionFinalizedDeclined control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSessionFinalizedDeclined As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gvFinalizedDeclined control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFinalizedDeclined As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSourceAdminFinalized control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAdminFinalized As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gvAdminFinalized control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAdminFinalized As Global.System.Web.UI.WebControls.GridView
End Class
