'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OverallStandings
    
    '''<summary>
    '''SqlDataSourceProgChair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceProgChair As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''gvProgChair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProgChair As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDataSourceSteeringComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSteeringComm As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''gvSteeringComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSteeringComm As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDataSourceSessionChair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSessionChair As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''gvSessionChair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSessionChair As Global.System.Web.UI.WebControls.GridView
End Class
