'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Sessions

    '''<summary>
    '''SqlDataSourceConference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceConference As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblConference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlConfList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConfList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSourceSessions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSessions As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceTopicGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceTopicGroup As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''FormViewSessions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormViewSessions As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''gvSessions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSessions As Global.System.Web.UI.WebControls.GridView
End Class
