'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SCGLinks
    
    '''<summary>
    '''lblSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSession As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkbtnSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnSession As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkConferences control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkConferences As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkOnSiteBadge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOnSiteBadge As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkSiteLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSiteLinks As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibit As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLinkSponsors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkSponsors As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitBalance As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkBoothStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBoothStaff As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkOrgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOrgID As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''ExhibitorLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExhibitorLookup As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkPOCLedger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPOCLedger As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkBoothTech control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBoothTech As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorMailingListFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorMailingListFee As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAttendeeBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAttendeeBalance As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAttendeeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAttendeeView As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAttendanceCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAttendanceCount As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkBadgeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBadgeReport As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProfDev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProfDev As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkShortCourseAtt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkShortCourseAtt As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkShortCourseOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkShortCourseOverview As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkShortCourseMaxCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkShortCourseMaxCap As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAbstracts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAbstracts As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAbstractReviewRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAbstractReviewRoles As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBalance As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAttendeeLedger2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAttendeeLedger2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorLedger2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorLedger2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkPOCLedger2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPOCLedger2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkUsers As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkQuery As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPerson As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkPersonManage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPersonManage As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDuplicate As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''SqlDataSourceParticipant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceParticipant As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''txtPersonLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonLookup As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''btnPersonLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPersonLookup As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblParticipationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParticipationID As Global.System.Web.UI.WebControls.Label
End Class
