'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteLinks
    
    '''<summary>
    '''SqlDataSourceConference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceConference As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblConference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConference As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlConfList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConfList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLinks As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lnkRegistration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRegistration As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkRegistrationTechReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRegistrationTechReg As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkRegistrationOneDayPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRegistrationOneDayPass As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkRegistrationExhibPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRegistrationExhibPass As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkRegistrationWaiver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRegistrationWaiver As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBalance As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkParticipant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkParticipant As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorSponsorRegistration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorSponsorRegistration As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorSponsorBoothReservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorSponsorBoothReservation As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorSponsorTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorSponsorTC As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorSponsorBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorSponsorBalance As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorSponsorLayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorSponsorLayout As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorBoothLayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorBoothLayout As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorBoothReservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorBoothReservation As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorTC As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorBalance As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkExhibitorStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExhibitorStaff As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkLearningLab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLearningLab As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkShortCourseProposal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkShortCourseProposal As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkShortCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkShortCourse As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkShortCourseBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkShortCourseBalance As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAbstract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAbstract As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAbstractReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAbstractReview As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProfDev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProfDev As Global.System.Web.UI.WebControls.HyperLink
End Class
