'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AttendanceCount

    '''<summary>
    '''SqlDataSourceConference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceConference As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblConference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlConfList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConfList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSourceAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAttendance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gvAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAttendance As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSourceRegType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRegType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gvRegType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRegType As Global.System.Web.UI.WebControls.GridView
End Class
