'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BalanceSummary

    '''<summary>
    '''SqlDataSourceConference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceConference As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblConference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlConfList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConfList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSourceReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceReg As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gvReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvReg As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSourceBooth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceBooth As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gvBooth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvBooth As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSourceShortCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceShortCourse As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gvShortCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvShortCourse As Global.System.Web.UI.WebControls.GridView
End Class
